### ISSUE TITLE
Getting error after updating from 12.0.4 to 12.0.7: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by ykessler** [mogest/prawn-svg#27]
We're getting the following error:

```
undefined method `gsub' for nil:NilClass
```

Trace:

```
prawn-svg (0.12.0.7) lib/prawn/svg/font.rb:40:in `block in load_external_fonts'
prawn-svg (0.12.0.7) lib/prawn/svg/font.rb:37:in `each'
prawn-svg (0.12.0.7) lib/prawn/svg/font.rb:37:in `load_external_fonts'
prawn-svg (0.12.0.7) lib/prawn/svg/interface.rb:34:in `initialize'
prawn-svg (0.12.0.7) lib/prawn/svg/extension.rb:18:in `new'
prawn-svg (0.12.0.7) lib/prawn/svg/extension.rb:18:in `svg'
```

This is happening on our local OSX 10.6.8 development box with code that worked fine with prawn-svg 12.0.4. Interestingly, when we deploy to Heroku, the 12.0.7 version does not error out, only our develpment box has been affected.
